### ISSUE TITLE
Symlink instead of copying

### ISSUE THREAD

**Issue by riyaz-ali** [vinitkumar/.vim#6]
Why not use `ln -s` instead of `cp` in `install.sh` <sup>[[source]](https://github.com/vinitkumar/.vim/blob/master/install.sh#L9-L10)</sup>? That way if there's an update in the `vimrc` (or `gvimrc`) file (and we do `git pull`), we won't have to `cp` the stuff again?

**Comment by vinitkumar** [comment]
Great idea. Feel free to send a PR
